version: '3.9'

services:
  redis:
    container_name: redis
    image: redis:latest
    ports:
      - 6379:6379

  app:
    container_name: dispatcher
    build: .
    environment:
      REDIS_URL: redis://redis:6379
    command: uvicorn main:app --host 0.0.0.0 --port 80
    volumes:
      - .:/app